alias: Room Light Control (Motion + Manual Modes) V2
description: >
  Unified automation that handles ON/OFF, motion lighting, and Hue dimmer switch
  control for any room. Automatically controls lights in the same area as the automation.
variables:
  # Self-aware variables
  room_area: "{{ this.area_id }}"
  lights_target:
    area_id: "{{ this.area_id }}"
  motion_entities: >
    {{ expand(area_entities(this.area_id))
        | selectattr('domain', 'equalto', 'binary_sensor')
        | selectattr('attributes.device_class', 'equalto', 'motion')
        | map(attribute='entity_id') | list }}
  status_dropdown: >
    {{ expand(area_entities(this.area_id))
        | selectattr('domain', 'equalto', 'input_select')
        | selectattr('entity_id', 'search', 'light_status')
        | map(attribute='entity_id') | first }}

triggers:
  # Motion trigger
  - trigger: state
    id: MOTION
    entity_id: "{{ motion_entities }}"
    from: "off"
    to: "on"

  # Dropdown ON / OFF triggers
  - trigger: state
    id: SWITCH_ON
    entity_id: "{{ status_dropdown }}"
    to: "ON"
  - trigger: state
    id: SWITCH_OFF
    entity_id: "{{ status_dropdown }}"
    to: "OFF"

  # Hue switch triggers
  - trigger: event
    id: SWITCH_ON
    event_type: hue_event
    event_data:
      type: initial_press
      subtype: 1
  - trigger: event
    id: SWITCH_OFF
    event_type: hue_event
    event_data:
      type: initial_press
      subtype: 4
  # Only respond to the Hue switch in this same area
  - condition: template
    value_template: >
      {% set dev = device_id(trigger.event.data.device_id) %}
      {{ area_id(dev) == this.area_id }}

actions:
  - choose:
      # --- Hue or Dropdown ON ---
      - conditions:
          - condition: trigger
            id: SWITCH_ON
        sequence:
          - action: input_select.select_option
            target:
              entity_id: "{{ status_dropdown }}"
            data:
              option: "ON"
          - action: light.turn_on
            target: "{{ lights_target }}"
            data: {}

      # --- Hue or Dropdown OFF ---
      - conditions:
          - condition: trigger
            id: SWITCH_OFF
        sequence:
          - action: input_select.select_option
            target:
              entity_id: "{{ status_dropdown }}"
            data:
              option: "OFF"
          - action: light.turn_off
            target: "{{ lights_target }}"
            data: {}

      # --- Motion Logic ---
      - conditions:
          - condition: trigger
            id: MOTION
          - condition: template
            value_template: >
              {{ states(status_dropdown) in [
                'MOTION TEST 15 SEC',
                'MOTION 5 MIN',
                'MOTION 10 MIN',
                'MOTION 30 MIN'
              ] }}
        sequence:
          - action: light.turn_on
            target: "{{ lights_target }}"
            data: {}

          # Timeout variants
          - choose:
              - conditions:
                  - condition: state
                    entity_id: "{{ status_dropdown }}"
                    state: MOTION TEST 15 SEC
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: "{{ motion_entities }}"
                        from: "on"
                        to: "off"
                        for:
                          seconds: 15
                  - action: light.turn_off
                    target: "{{ lights_target }}"
                    data: {}

              - conditions:
                  - condition: state
                    entity_id: "{{ status_dropdown }}"
                    state: MOTION 5 MIN
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: "{{ motion_entities }}"
                        from: "on"
                        to: "off"
                        for:
                          minutes: 5
                  - action: light.turn_off
                    target: "{{ lights_target }}"
                    data: {}

              - conditions:
                  - condition: state
                    entity_id: "{{ status_dropdown }}"
                    state: MOTION 10 MIN
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: "{{ motion_entities }}"
                        from: "on"
                        to: "off"
                        for:
                          minutes: 10
                  - action: light.turn_off
                    target: "{{ lights_target }}"
                    data: {}

              - conditions:
                  - condition: state
                    entity_id: "{{ status_dropdown }}"
                    state: MOTION 30 MIN
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: "{{ motion_entities }}"
                        from: "on"
                        to: "off"
                        for:
                          minutes: 30
                  - action: light.turn_off
                    target: "{{ lights_target }}"
                    data: {}

mode: restart
