blueprint:
  name: Room Light Control V2 (Motion + Manual + Buttons)
  description: >
    Enhanced automation that controls room lights using motion, dropdown
    mode selection, and optional Hue dimmer buttons.
  domain: automation
  input:
    room_lights:
      name: Room Lights
      description: Lights or switches to control.
      selector:
        target:
          entity:
            domain: light

    motion_sensors:
      name: Motion Sensors
      description: One or more motion sensors for this room.
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class: motion

    mode_dropdown:
      name: Room Mode Dropdown
      description: Input select for ON, OFF, or MOTION modes.
      selector:
        entity:
          domain: input_select

    button_device:
      name: (Optional) Hue Dimmer Switch
      description: Optional Hue dimmer device for manual control.
      default: []
      selector:
        device: {}

triggers:
  - platform: state
    id: motion_trigger
    entity_id: !input motion_sensors
    from: "off"
    to: "on"

  - platform: state
    id: switch_on
    entity_id: !input mode_dropdown
    to: "ON"

  - platform: state
    id: switch_off
    entity_id: !input mode_dropdown
    to: "OFF"

  - platform: device
    device_id: !input button_device
    domain: hue
    type: initial_press
    subtype: 1
    id: button_on

  - platform: device
    device_id: !input button_device
    domain: hue
    type: initial_press
    subtype: 4
    id: button_off

  - platform: device
    device_id: !input button_device
    domain: hue
    type: long_release
    subtype: 3
    id: button_motion_10min

actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - switch_on
              - button_on
        sequence:
          - service: light.turn_on
            target: !input room_lights
          - service: input_select.select_option
            target:
              entity_id: !input mode_dropdown
            data:
              option: "ON"

      - conditions:
          - condition: trigger
            id:
              - switch_off
              - button_off
        sequence:
          - service: light.turn_off
            target: !input room_lights
          - service: input_select.select_option
            target:
              entity_id: !input mode_dropdown
            data:
              option: "OFF"

      - conditions:
          - condition: trigger
            id: button_motion_10min
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input mode_dropdown
            data:
              option: "MOTION 10 MIN"

      - conditions:
          - condition: trigger
            id: motion_trigger
          - condition: template
            value_template: >
              {% set mode = states[inputs.mode_dropdown] %}
              {{ mode in [
                'MOTION TEST 15 SEC',
                'MOTION 5 MIN',
                'MOTION 10 MIN',
                'MOTION 30 MIN'
              ] }}
        sequence:
          - service: light.turn_on
            target: !input room_lights
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: "MOTION TEST 15 SEC"
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          seconds: 15
                  - service: light.turn_off
                    target: !input room_lights

              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: "MOTION 5 MIN"
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 5
                  - service: light.turn_off
                    target: !input room_lights

              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: "MOTION 10 MIN"
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 10
                  - service: light.turn_off
                    target: !input room_lights

              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: "MOTION 30 MIN"
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 30
                  - service: light.turn_off
                    target: !input room_lights

mode: restart
