blueprint:
  name: Room Light Control (Motion + Manual Modes)
  description: >
    Controls room lighting with both motion sensors and manual switches. 
    Supports multiple motion durations and manual overrides.
  domain: automation
  input:
    light_target:
      name: Lights
      description: The light(s) or area to control.
      selector:
        target:
          entity:
            domain: light

    motion_sensors:
      name: Motion Sensors
      description: Motion sensors that trigger the lights.
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    status_dropdown:
      name: Light Mode Selector
      description: Input select controlling the mode (ON, OFF, MOTION, etc.).
      selector:
        entity:
          domain: input_select

    button_on:
      name: Manual On Button
      description: Optional input button to turn lights ON.
      default: []
      selector:
        entity:
          domain: input_button
          multiple: true

    button_off:
      name: Manual Off Button
      description: Optional input button to turn lights OFF.
      default: []
      selector:
        entity:
          domain: input_button
          multiple: true

    button_motion:
      name: Motion Mode Button
      description: Optional input button to toggle motion mode durations.
      default: []
      selector:
        entity:
          domain: input_button
          multiple: true

triggers:
  # Motion Detected
  - trigger: state
    id: MOTION
    entity_id: !input motion_sensors
    from: "off"
    to: "on"

  # Manual Buttons
  - trigger: state
    id: SWITCH_ON
    entity_id: !input button_on
  - trigger: state
    id: SWITCH_OFF
    entity_id: !input button_off
  - trigger: state
    id: BUTTON_MOTION
    entity_id: !input button_motion

  # Input Select Changes
  - trigger: state
    id: SWITCH_ON
    entity_id: !input status_dropdown
    to: "ON"
  - trigger: state
    id: SWITCH_OFF
    entity_id: !input status_dropdown
    to: "OFF"

actions:
  - choose:
      # --- Turn ON manually ---
      - conditions:
          - condition: trigger
            id: SWITCH_ON
        sequence:
          - action: light.turn_on
            target: !input light_target
          - action: input_select.select_option
            target:
              entity_id: !input status_dropdown
            data:
              option: "ON"

      # --- Turn OFF manually ---
      - conditions:
          - condition: trigger
            id: SWITCH_OFF
        sequence:
          - action: light.turn_off
            target: !input light_target
          - action: input_select.select_option
            target:
              entity_id: !input status_dropdown
            data:
              option: "OFF"

      # --- Motion Triggered ---
      - conditions:
          - condition: trigger
            id: MOTION
          - condition: template
            value_template: >
              {{ states(status_dropdown) in [
                'MOTION TEST 15 SEC',
                'MOTION 5 MIN',
                'MOTION 10 MIN',
                'MOTION 30 MIN'
              ] }}
        sequence:
          - action: light.turn_on
            target: !input light_target
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION TEST 15 SEC"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          seconds: 15
                  - action: light.turn_off
                    target: !input light_target
              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION 5 MIN"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 5
                  - action: light.turn_off
                    target: !input light_target
              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION 10 MIN"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 10
                  - action: light.turn_off
                    target: !input light_target
              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION 30 MIN"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 30
                  - action: light.turn_off
                    target: !input light_target

      # --- Toggle Motion Duration via Button ---
      - conditions:
          - condition: trigger
            id: BUTTON_MOTION
        sequence:
          - if:
              - condition: state
                entity_id: !input status_dropdown
                state: "MOTION 10 MIN"
            then:
              - action: input_select.select_option
                target:
                  entity_id: !input status_dropdown
                data:
                  option: "MOTION 30 MIN"
            else:
              - action: input_select.select_option
                target:
                  entity_id: !input status_dropdown
                data:
                  option: "MOTION 10 MIN"

mode: restart
