blueprint:
  name: Room Light Control (Motion + Manual + Hue Switch)
  description: >
    Controls lights using motion sensors, manual buttons, and optionally a Hue dimmer switch.
    Supports motion durations (15s, 5min, 10min, 30min) and manual ON/OFF overrides.
  domain: automation

  input:
    light_target:
      name: Lights
      description: The light(s) or area to control.
      selector:
        target:
          entity:
            domain: light

    motion_sensors:
      name: Motion Sensors
      description: Motion sensors that trigger the lights.
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    status_dropdown:
      name: Light Mode Selector
      description: Input select controlling the mode (ON, OFF, MOTION TEST 15 SEC, etc.).
      selector:
        entity:
          domain: input_select

    button_on:
      name: Manual On Button
      description: Optional input button to turn lights ON.
      default: []
      selector:
        entity:
          domain: input_button
          multiple: true

    button_off:
      name: Manual Off Button
      description: Optional input button to turn lights OFF.
      default: []
      selector:
        entity:
          domain: input_button
          multiple: true

    button_motion:
      name: Motion Mode Button
      description: Optional input button to toggle motion mode durations.
      default: []
      selector:
        entity:
          domain: input_button
          multiple: true

    hue_switch:
      name: Hue Dimmer Switch
      description: >
        Optional Hue dimmer switch device to control lights.
        (Button 1 = ON, Button 4 = OFF, long press Button 3 = toggle motion mode)
      default: []
      selector:
        device: {}

triggers:
  # --- Motion ---
  - trigger: state
    id: MOTION
    entity_id: !input motion_sensors
    from: "off"
    to: "on"

  # --- Manual Input Buttons ---
  - trigger: state
    id: SWITCH_ON
    entity_id: !input button_on
  - trigger: state
    id: SWITCH_OFF
    entity_id: !input button_off
  - trigger: state
    id: BUTTON_MOTION
    entity_id: !input button_motion

  # --- Hue Switch Buttons ---
  - trigger: device
    id: SWITCH_ON
    device_id: !input hue_switch
    domain: hue
    type: initial_press
    subtype: 1
  - trigger: device
    id: SWITCH_OFF
    device_id: !input hue_switch
    domain: hue
    type: initial_press
    subtype: 4
  - trigger: device
    id: BUTTON_MOTION_10MIN
    device_id: !input hue_switch
    domain: hue
    type: long_release
    subtype: 3

  # --- Input Select Change (manual control) ---
  - trigger: state
    id: SWITCH_ON
    entity_id: !input status_dropdown
    to: "ON"
  - trigger: state
    id: SWITCH_OFF
    entity_id: !input status_dropdown
    to: "OFF"

actions:
  - choose:
      # --- Turn ON ---
      - conditions:
          - condition: trigger
            id: SWITCH_ON
        sequence:
          - action: light.turn_on
            target: !input light_target
          - action: input_select.select_option
            target:
              entity_id: !input status_dropdown
            data:
              option: "ON"

      # --- Turn OFF ---
      - conditions:
          - condition: trigger
            id: SWITCH_OFF
        sequence:
          - action: light.turn_off
            target: !input light_target
          - action: input_select.select_option
            target:
              entity_id: !input status_dropdown
            data:
              option: "OFF"

      # --- Motion Triggered ---
      - conditions:
          - condition: trigger
            id: MOTION
          - condition: or
            conditions:
              - condition: state
                entity_id: !input status_dropdown
                state: "MOTION TEST 15 SEC"
              - condition: state
                entity_id: !input status_dropdown
                state: "MOTION 5 MIN"
              - condition: state
                entity_id: !input status_dropdown
                state: "MOTION 10 MIN"
              - condition: state
                entity_id: !input status_dropdown
                state: "MOTION 30 MIN"
        sequence:
          - action: light.turn_on
            target: !input light_target
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION TEST 15 SEC"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          seconds: 15
                  - action: light.turn_off
                    target: !input light_target

              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION 5 MIN"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 5
                  - action: light.turn_off
                    target: !input light_target

              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION 10 MIN"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 10
                  - action: light.turn_off
                    target: !input light_target

              - conditions:
                  - condition: state
                    entity_id: !input status_dropdown
                    state: "MOTION 30 MIN"
                sequence:
                  - wait_for_trigger:
                      - trigger: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 30
                  - action: light.turn_off
                    target: !input light_target

      # --- Motion Mode Toggle via Hue or Button ---
      - conditions:
          - condition: trigger
            id:
              - BUTTON_MOTION
              - BUTTON_MOTION_10MIN
        sequence:
          - if:
              - condition: state
                entity_id: !input status_dropdown
                state: "MOTION 10 MIN"
            then:
              - action: input_select.select_option
                target:
                  entity_id: !input status_dropdown
                data:
                  option: "MOTION 30 MIN"
            else:
              - action: input_select.select_option
                target:
                  entity_id: !input status_dropdown
                data:
                  option: "MOTION 10 MIN"

mode: restart
