blueprint:
  name: Room Light Control (Motion + Manual + Optional Hue)
  description: >
    Controls room lights using motion sensors, an input_select dropdown for mode,
    and optionally a Hue dimmer (via state or event-based approach).
  domain: automation
  input:
    room_lights:
      name: Room Lights
      description: Lights or switches to control.
      selector:
        target:
          entity:
            domain: light

    motion_sensors:
      name: Motion Sensors (Optional)
      description: Motion sensors to trigger lighting. Leave empty if not used.
      default: []
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class: motion

    mode_dropdown:
      name: Mode Dropdown
      description: Input select controlling light mode (ON, OFF, MOTION).
      selector:
        entity:
          domain: input_select

triggers:
  - platform: state
    id: MOTION
    entity_id: !input motion_sensors
    from: "off"
    to: "on"

  - platform: state
    id: SWITCH_ON
    entity_id: !input mode_dropdown
    to: "ON"

  - platform: state
    id: SWITCH_OFF
    entity_id: !input mode_dropdown
    to: "OFF"

variables:
  motion_entities: !input motion_sensors
  lights_target: !input room_lights
  status_dropdown: !input mode_dropdown

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: SWITCH_ON
        sequence:
          - action: light.turn_on
            target: !input room_lights
            data: {}
          - action: input_select.select_option
            target:
              entity_id: !input mode_dropdown
            data:
              option: "ON"

      - conditions:
          - condition: trigger
            id: SWITCH_OFF
        sequence:
          - action: light.turn_off
            target: !input room_lights
            data: {}
          - action: input_select.select_option
            target:
              entity_id: !input mode_dropdown
            data:
              option: "OFF"

      - conditions:
          - condition: trigger
            id: MOTION
          - condition: template
            value_template: >
              {{ states(status_dropdown) in [
                'MOTION TEST 15 SEC',
                'MOTION 5 MIN',
                'MOTION 10 MIN',
                'MOTION 30 MIN'
              ] }}
        sequence:
          - action: light.turn_on
            target: !input room_lights
            data: {}
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: MOTION TEST 15 SEC
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          seconds: 15
                  - action: light.turn_off
                    target: !input room_lights
                    data: {}

              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: MOTION 5 MIN
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 5
                  - action: light.turn_off
                    target: !input room_lights
                    data: {}

              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: MOTION 10 MIN
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 10
                  - action: light.turn_off
                    target: !input room_lights
                    data: {}

              - conditions:
                  - condition: state
                    entity_id: !input mode_dropdown
                    state: MOTION 30 MIN
                sequence:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        from: "on"
                        to: "off"
                        for:
                          minutes: 30
                  - action: light.turn_off
                    target: !input room_lights
                    data: {}

mode: restart
